sudo: required
dist: trusty
language: node_js
node_js:
  - '8'

cache: npm
jobs:
  include:
    - stage: install
      script: npm install
    - stage: build
      script:
      - npm run build
      - npm run lint
    - stage: test
      script: npm run test